# Generated by Django 5.0.4 on 2024-07-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
