# Generated by Django 5.0.4 on 2024-07-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0002_appointmentslots_is_blocked'),
        ('patient', '0009_patientvarrydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslots',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patientvarrydetails'),
        ),
    ]
