# Generated by Django 5.0.4 on 2024-08-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0003_alter_appointmentslots_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
