# Generated by Django 5.0.4 on 2024-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0004_appointmentslots_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='appointment_type',
            field=models.CharField(choices=[('walk-in', 'Walk-In'), ('online', 'Online'), ('follow-up', 'Follow-Up')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='appointmentslots',
            name='is_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
