# Generated by Django 5.0.4 on 2024-08-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0005_appointmentslots_appointment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
