# Generated by Django 5.0.4 on 2024-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0006_appointmentslots_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
