# Generated by Django 5.0.4 on 2024-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0007_appointmentslots_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='reminder_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
