# Generated by Django 4.2.16 on 2024-09-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_symptoms_doctordetail_hospital_name_and_more'),
        ('doctorappointment', '0008_appointmentslots_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslots',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.personalsdetails'),
        ),
    ]
