# Generated by Django 4.2.16 on 2024-09-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0009_alter_appointmentslots_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
