# Generated by Django 4.2.16 on 2024-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0012_alter_appointmentslots_appointment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslots',
            name='is_appointment',
        ),
        migrations.AddField(
            model_name='appointmentslots',
            name='is_online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentslots',
            name='appointment_type',
            field=models.CharField(choices=[('walk-in', 'Walk-In'), ('online', 'Online'), ('follow-up', 'Follow-Up')], default='online', max_length=20),
        ),
    ]
