# Generated by Django 4.2.16 on 2024-10-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0013_remove_appointmentslots_is_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslots',
            name='is_online',
        ),
    ]
