# Generated by Django 4.2.16 on 2024-10-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0014_remove_appointmentslots_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslots',
            name='consultation_type',
            field=models.CharField(choices=[('walk-in', 'Walk-In'), ('online', 'Online')], default='online', max_length=20),
        ),
    ]
