# Generated by Django 4.2.16 on 2024-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0016_alter_appointmentslots_consultation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslots',
            name='consultation_type',
            field=models.CharField(blank=True, choices=[('walk-in', 'Walk-In'), ('online', 'Online')], default='walk-in', max_length=20, null=True),
        ),
    ]
