# Generated by Django 5.0.4 on 2024-07-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinicdetails_created_at_clinicdetails_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
