# Generated by Django 4.2.16 on 2024-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_clinicdetails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicregister',
            name='password',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
