# Generated by Django 4.2.16 on 2024-11-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_clinicregister_is_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicregister',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
