# Generated by Django 5.0.4 on 2024-06-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_delete_appointmentslot'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionregister',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorregister'),
            preserve_default=False,
        ),
    ]
