# Generated by Django 4.2.16 on 2024-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_receptionregister_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionregister',
            name='password',
            field=models.CharField(default=2, max_length=225),
            preserve_default=False,
        ),
    ]
