# Generated by Django 4.2.16 on 2024-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_receptionregister_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionregister',
            name='password',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
