# Generated by Django 4.2.16 on 2024-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_alter_receptionregister_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionregister',
            name='is_reset',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
