# Generated by Django 4.2.16 on 2024-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_receptionregister_is_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionregister',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
