# Generated by Django 5.0.4 on 2024-06-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookSlot',
        ),
    ]
