# Generated by Django 5.0.4 on 2024-06-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientdetails_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='user',
            new_name='patient',
        ),
    ]
