# Generated by Django 5.0.4 on 2024-07-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_user_patientdetails_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('oxygen_level', models.FloatField(blank=True, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=255, null=True)),
                ('symptoms_comment', models.TextField(blank=True, null=True)),
                ('body_temperature', models.FloatField(blank=True, null=True)),
                ('mobile_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientregister')),
            ],
        ),
    ]
