# Generated by Django 5.0.4 on 2024-07-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='document_type',
            field=models.CharField(choices=[('report', 'Report'), ('prescription', 'Priscription'), ('invoice', 'Invoice')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
