# Generated by Django 5.0.4 on 2024-07-17 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0001_initial'),
        ('patient', '0006_patientdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprescription',
            name='appoinment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctorappointment.appointmentslots'),
            preserve_default=False,
        ),
    ]
