# Generated by Django 5.0.4 on 2024-07-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patientprescription_appoinment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprescription',
            old_name='appoinment',
            new_name='appointment',
        ),
    ]
