# Generated by Django 5.0.4 on 2024-07-25 12:09

import django.db.models.deletion
import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0002_appointmentslots_is_blocked'),
        ('patient', '0008_rename_appoinment_patientprescription_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVarryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('blood_group', models.CharField(max_length=5)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=patient.models.save_user_pic)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorappointment.appointmentslots')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientregister')),
            ],
        ),
    ]
