# Generated by Django 5.0.4 on 2024-07-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0003_alter_appointmentslots_booked_by'),
        ('patient', '0009_patientvarrydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctorappointment.appointmentslots'),
            preserve_default=False,
        ),
    ]
