# Generated by Django 5.0.4 on 2024-07-30 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patientrecord_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientvarrydetails'),
        ),
    ]
