# Generated by Django 5.0.4 on 2024-08-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0007_appointmentslots_is_canceled'),
        ('patient', '0011_alter_patientprescription_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='height',
            new_name='heart_rate',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='weight',
            new_name='hemoglobin',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='mobile_number',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='symptoms_comment',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='pulse_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorappointment.appointmentslots'),
        ),
    ]
