# Generated by Django 5.0.4 on 2024-08-10 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_rename_height_patientrecord_heart_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientvarrydetails'),
        ),
    ]
