# Generated by Django 5.0.4 on 2024-08-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_rename_patient_patientdocumentbyappointmentid_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdocumentbyappointmentid',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
