# Generated by Django 5.0.4 on 2024-08-13 11:02

import django.db.models.deletion
import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0007_appointmentslots_is_canceled'),
        ('patient', '0018_alter_patientdocumentbyappointmentid_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocumentById',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=patient.models.patient_report)),
                ('patient_name', models.CharField(max_length=250)),
                ('document_date', models.DateField()),
                ('document_type', models.CharField(choices=[('report', 'Report'), ('prescription', 'Priscription'), ('invoice', 'Invoice')], max_length=50)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorappointment.appointmentslots')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientDocumentByAppointmentId',
        ),
    ]
