# Generated by Django 5.0.4 on 2024-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_patientdocumentbyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocumentbyid',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='path/to/upload/'),
        ),
        migrations.AlterField(
            model_name='patientdocumentbyid',
            name='document_type',
            field=models.CharField(choices=[('report', 'Report'), ('prescription', 'Prescription'), ('invoice', 'Invoice')], max_length=50),
        ),
    ]
