# Generated by Django 5.0.4 on 2024-08-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('patient', '0020_alter_patientdocumentbyid_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocumentbyid',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='patientdocumentbyid',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
