# Generated by Django 5.0.4 on 2024-08-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_patientdocumentbyid_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocumentbyid',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='patientdocumentbyid',
            name='object_id',
        ),
    ]
