# Generated by Django 5.0.4 on 2024-08-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_remove_patientdocumentbyid_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocumentbyid',
            name='uploaded_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdocumentbyid',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='document_by_id'),
        ),
    ]
