# Generated by Django 5.0.4 on 2024-08-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_patientdocumentbyid_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='record_date',
            field=models.DateField(default='2024-08-02'),
        ),
    ]
