# Generated by Django 5.0.4 on 2024-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_patientrecord_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='record_date',
            field=models.DateField(),
        ),
    ]
