# Generated by Django 5.0.4 on 2024-08-26 11:59

import patient.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0026_patientprescriptionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocumentbyid',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=patient.models.document_by_id),
        ),
    ]
