# Generated by Django 5.0.4 on 2024-09-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0028_rename_hemoglobin_patientrecord_sugar_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
