# Generated by Django 5.0.4 on 2024-09-06 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorappointment', '0007_appointmentslots_is_canceled'),
        ('patient', '0030_remove_patientprescription_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorappointment.appointmentslots'),
        ),
    ]
