# Generated by Django 5.0.4 on 2024-09-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0031_alter_time_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='patient',
            new_name='appointment',
        ),
    ]
