# Generated by Django 5.0.4 on 2024-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0032_rename_patient_time_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregister',
            name='password',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
