# Generated by Django 4.2.16 on 2024-10-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0035_patientprescription_time_delete_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='record_date',
        ),
    ]
