# Generated by Django 4.2.16 on 2024-10-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0036_remove_patientrecord_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
