# Generated by Django 4.2.16 on 2024-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0038_patientvarrydetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvarrydetails',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
