# Generated by Django 4.2.16 on 2024-11-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0039_alter_patientvarrydetails_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvarrydetails',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
