# Generated by Django 4.2.16 on 2024-11-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0040_alter_patientvarrydetails_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregister',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
