# Generated by Django 4.2.16 on 2024-11-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0041_alter_patientregister_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvarrydetails',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
