# Generated by Django 4.2.16 on 2024-11-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0042_alter_patientdetails_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprescription',
            name='patient',
        ),
    ]
