# Generated by Django 5.0.4 on 2024-07-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdoctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdoctordetail',
            old_name='clinic',
            new_name='subdoctor',
        ),
        migrations.DeleteModel(
            name='ClinicDetail',
        ),
    ]
