# Generated by Django 5.0.4 on 2024-07-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_rename_qualification_doctordetail_qualifications'),
        ('subdoctor', '0002_rename_clinic_subdoctordetail_subdoctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdoctorregister',
            name='doctor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorregister'),
            preserve_default=False,
        ),
    ]
