# Generated by Django 5.0.4 on 2024-06-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctordetail_registration_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointmentslot',
        ),
    ]
