# Generated by Django 5.0.4 on 2024-06-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_delete_appointmentslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctordetail',
            name='qualification',
        ),
        migrations.AddField(
            model_name='doctordetail',
            name='qualification',
            field=models.ManyToManyField(blank=True, to='doctor.qualification'),
        ),
    ]
