# Generated by Django 5.0.4 on 2024-06-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_qualification_remove_doctordetail_qualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordetail',
            old_name='qualification',
            new_name='qualifications',
        ),
    ]
