# Generated by Django 5.0.4 on 2024-07-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_rename_qualification_doctordetail_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetail',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='name',
        ),
        migrations.AddField(
            model_name='qualification',
            name='doctor',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='doctor.doctorregister'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('PhD', 'PhD'), ('Diploma', 'Diploma'), ('Fellowship', 'Fellowship')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
