# Generated by Django 5.0.4 on 2024-07-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_remove_doctordetail_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
