# Generated by Django 5.0.4 on 2024-07-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_doctordetail_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
