# Generated by Django 5.0.4 on 2024-09-12 11:27

import django.db.models.deletion
import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctorregister_is_active_doctorregister_is_verified'),
        ('doctorappointment', '0008_appointmentslots_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctordetail',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='password',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='doctor.doctorregister'),
        ),
        migrations.AlterField(
            model_name='doctorregister',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('is_update', models.BooleanField(blank=True, default=False, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorregister')),
            ],
        ),
        migrations.CreateModel(
            name='Opd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to=doctor.models.save_doc)),
                ('start_day', models.TextField(blank=True, null=True)),
                ('end_day', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_update', models.BooleanField(blank=True, default=False, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorregister')),
            ],
        ),
        migrations.CreateModel(
            name='OpdDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.TextField()),
                ('end_day', models.TextField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorregister')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=6)),
                ('registration_no', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150)),
                ('experience', models.IntegerField()),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=doctor.models.doctor_pic)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('languages_spoken', models.CharField(blank=True, max_length=255, null=True)),
                ('is_update', models.BooleanField(blank=True, default=False, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorregister')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=10)),
                ('more_options', models.TextField(blank=True, null=True)),
                ('symptom_date', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorappointment.appointmentslots')),
                ('symptoms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.symptoms')),
            ],
        ),
    ]
