# Generated by Django 4.2.16 on 2024-09-27 12:32

from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_symptoms_doctordetail_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsdetails',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.save_doc),
        ),
    ]
