# Generated by Django 4.2.16 on 2024-09-30 09:07

from django.db import migrations, models
import django.db.models.deletion
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_personalsdetails_doc_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='doctor.doctorregister'),
        ),
        migrations.AlterField(
            model_name='personalsdetails',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.save_doc),
        ),
        migrations.AlterField(
            model_name='personalsdetails',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='doctor.doctorregister'),
        ),
    ]
