# Generated by Django 4.2.16 on 2024-10-15 06:51

from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_alter_personalsdetails_doc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='is_created',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-15T12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personalsdetails',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.save_doc),
        ),
    ]
