# Generated by Django 4.2.16 on 2024-10-19 09:37

from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_doctorregister_is_created_doctorregister_is_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='consultation_fee',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalsdetails',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.save_doc),
        ),
    ]
