# Generated by Django 4.2.16 on 2024-11-04 07:18

from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0036_alter_personalsdetails_doc_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomsdetail',
            name='symptom_date',
        ),
        migrations.AlterField(
            model_name='personalsdetails',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.save_doc),
        ),
    ]
