# Generated by Django 4.2.16 on 2024-11-04 07:25

from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0037_remove_symptomsdetail_symptom_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregister',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='personalsdetails',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.models.save_doc),
        ),
    ]
